# Generated by Django 5.0 on 2024-03-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
