# Generated by Django 5.0.1 on 2024-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0006_review_delete_message_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_pic_One', models.ImageField(upload_to='project_images')),
                ('project_pic_Two', models.ImageField(upload_to='project_images')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
