# Generated by Django 5.0.1 on 2024-04-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0009_rename_project_pic_one_createcard_after_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcard',
            name='facebook_url',
            field=models.URLField(null=True),
        ),
    ]
