# Generated by Django 5.0.1 on 2024-04-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0010_createcard_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcard',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
