# Generated by Django 5.0.1 on 2024-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0013_alter_createcard_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcard',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createcard',
            name='header',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
