# Generated by Django 5.0.1 on 2024-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0007_createcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcard',
            name='project_pic_One',
            field=models.ImageField(upload_to='capStoneApp/static/project_images'),
        ),
        migrations.AlterField(
            model_name='createcard',
            name='project_pic_Two',
            field=models.ImageField(upload_to='capStoneApp/static/project_images'),
        ),
    ]
