# Generated by Django 5.0.1 on 2024-04-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0008_alter_createcard_project_pic_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcard',
            old_name='project_pic_One',
            new_name='after_Pic',
        ),
        migrations.RenameField(
            model_name='createcard',
            old_name='project_pic_Two',
            new_name='before_Pic',
        ),
    ]
