# Generated by Django 5.0.1 on 2024-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0012_createcard_header_alter_createcard_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcard',
            name='header',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
