# Generated by Django 5.0.1 on 2024-04-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0014_alter_createcard_facebook_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcard',
            old_name='facebook_url',
            new_name='url',
        ),
    ]
