# Generated by Django 4.2 on 2024-04-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0016_alter_review_rating'),
        ('capStoneApp', '0016_chat'),
    ]

    operations = [
    ]

# Generated by Django 5.0.1 on 2024-04-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0016_alter_review_rating'),
        ('capStoneApp', '0016_chat'),
    ]

    operations = [
    ]
