# Generated by Django 5.0.1 on 2024-04-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0017_merge_0016_alter_review_rating_0016_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
