<<<<<<< HEAD
# Generated by Django 5.0 on 2024-04-26 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.2 on 2024-04-26 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 6acab63d8a43d062274f9b59c7d746c394963138


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('capStoneApp', '0018_delete_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capStoneApp', '0018_delete_chat'),
>>>>>>> 6acab63d8a43d062274f9b59c7d746c394963138
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
