# Generated by Django 4.2 on 2024-04-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0020_review_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('filename', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
