# Generated by Django 4.2 on 2024-04-29 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capStoneApp', '0021_requestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under-Development', 'Under Development'), ('Finished', 'Finished')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
