# Generated by Django 4.2 on 2024-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capStoneApp', '0022_requestmodel_status_requestmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Finished', 'Finished')], default='Pending', max_length=20),
        ),
    ]
